# Variables:
#   %anchor-name%, %cool-down-left%, %command%, %name%, %permission%, %world-name%
#   %add%, %help%, %list%, %remove%, %set%, %teleport%

# Colors:
#   BLACK = &0, DARK_BLUE = &1, DARK_GREEN = &2, DARK_AQUA = &3
#   DARK_RED = &4, DARK_PURPLE = &5, GOLD = &6, GRAY = &7
#   DARK_GRAY = &8, BLUE = &9, GREEN = &a, AQUA = &b
#   RED = &c, LIGHT_PURPLE = &d, YELLOW = &e, WHITE = &f

# Formats:
#   OBFUSCATED = &k, BOLD = &l, STRIKETHROUGH = &m,
#   UNDERLINE = &n, ITALIC = &o, RESET = &r
message:
  cannot-execute-in-console: "&cYou can't execute this command in console!"
  cannot-teleport-cross-world: "&cYou can't teleport to another world! name: %world-name%"
  command-in-cool-down: "&cYou can use BetterTP command after %cool-down-left%s!"
  invalid-argument: "&cInvalid argument! command: %argument%"
  invalid-command: "&cInvalid command! command: %command%"
  no-command-permission: "&cYou don't have permission to do this! permission: %permission%"
  anchor-added: "&aAnchor added! name: %anchor-name%"
  anchor-edited: "&aAnchor edited! name: %anchor-name%"
  anchor-existed: "&cAnchor existed! name: %anchor-name%"
  anchor-list-title: "&e--------- &rAnchors &e---------&r"
  anchor-item-form: "+ %anchor-name%"
  anchor-not-found: "&cAnchor not found! name: %anchor-name%"
  anchor-removed: "&aAnchor removed! name: %anchor-name%"
  no-anchor-found: "&cThere is no anchor on this server!"
  player-teleport: "&aTeleport to %world-name%"
  world-not-found: "&cWorld not found! name: %world-name%"
  help:
    - "&e--------- &rHelp: BetterTP &e---------------------------&r"
    - "&7Below is a list of all BetterTP commands:&r"
    - "&6/btp add <name>: &rAdd an anchor at player's location"
    - "&6/btp help: &rShow this list"
    - "&6/btp list: &rList all anchors"
    - "&6/btp remove <name>: &rRemove an assigned anchor"
    - "&6/btp set <name>: &rSet location of an assigned anchor to player's location"
    - "&6/btp tp <name>: &rTeleport to an assigned anchor"
  # Variables:
  #   %position-x%, %position-y%, %position-z%, %rotation-yaw%, %rotation-pitch%, %world-name%, %author%, %public%
  information:
    - "&e--------- &rInformation: %world-name% &e---------&r"
    - "&rPosition: %position-x% / %position-y% / %position-z%"
    - "&rFacing: (%rotation-yaw% / %rotation-pitch%)"
    - "&rWorld: %world-name%"
    - "&rAccess: %access%"
    - "&rCreated by %author%"
    - ""
    - "&7[Click To Teleport]"

setting:
  command:
    # To prevent players from spamming commands, unit = millisecond
    min-command-cool-down: 1000
    # To prevent commands from being executed from console
    only-execute-by-players: true
  teleport:
    # To prevent player from teleporting cross world
    teleport-cross-world: false
    # To prevent player from teleporting to private anchor
    teleport-private-anchor: false





